services:
  - type: web
    name: openremote-manager
    env: docker
    dockerfilePath: ./manager/Dockerfile
    plan: starter
    healthCheckPath: /api/master/info
    envVars:
      - key: OR_HOSTNAME
        value: openremote-manager.onrender.com
      - key: OR_SSL_PORT
        value: "443"
      - key: OR_DEV_MODE
        value: "false"
      - key: SETUP_ADMIN_PASSWORD
        value: admin
      - key: SETUP_WIPE_CLEAN_INSTALL
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: openremote-postgres
          property: connectionString

  - type: web
    name: openremote-keycloak
    env: docker
    dockerfilePath: ./deployment/keycloak/Dockerfile
    plan: starter
    envVars:
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: admin
      - key: KC_DB
        value: postgres
      - key: KC_DB_URL
        fromDatabase:
          name: openremote-postgres
          property: connectionString
      - key: KC_HOSTNAME
        value: openremote-keycloak.onrender.com

databases:
  - name: openremote-postgres
    databaseName: openremote
    user: postgres
    plan: starter
